openapi: 3.0.0
info:
  title: Arkanoid API
  description: API for Arkanoid game
  version: 1.0.0
  contact:
    name: Vladimir Mazhirin
    url: https://github.com/vladimirm85
    email: vladimirm85@gmail.com
servers:
  - url: https://arkanoid-rss-be.herokuapp.com
    description: Production server
paths:
  /saves:
    get:
      summary: Get all saves
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of Save.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Save'
        '500':
          description: error
components:
  schemas:
    Save:
      type: object
      properties:
        _id:
          type: string
          example: 60048e26a8486d510406b33f
        saveData:
          type: object
        userId:
          type: string
          example: 600485e573f5ce001796f558
        createdAt:
          type: string
          format: date
          example: 2021-01-17T19:21:10.492+00:00
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
