openapi: 3.0.0
info:
  title: Arkanoid API
  description: API for Arkanoid game
  version: 1.0.0
  contact:
    name: Vladimir Mazhirin
    url: https://github.com/vladimirm85
    email: vladimirm85@gmail.com
servers:
  - url: https://arkanoid-rss-be.herokuapp.com
    description: Production server



paths:


  /saves:

    get:
      summary: Takes user ID from token and returns all user saves
      operationId: getAllSaves
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/Saves'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'

    post:
      summary: Takes user ID from the token, Save data from the body and creates user Save
      operationId: createSave
      security:
        - bearerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/SaveData'
      responses:
        '201':
          $ref: '#/components/responses/Save'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'

    put:
      summary: Takes user ID from the token, Save ID from the parameters, Save data from the body and creates user Save
      operationId: updateSave
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SaveId'
      requestBody:
        $ref: '#/components/requestBodies/SaveData'
      responses:
        '200':
          $ref: '#/components/responses/Save'
        '404':
          $ref: '#/components/responses/SaveNotFound'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'

  /saves/{id}:

    get:
      summary: Takes user ID from the token, Save ID from the parameters and returns user Save
      operationId: getSaveById
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SaveId'
      responses:
        '200':
          $ref: '#/components/responses/Save'
        '404':
          $ref: '#/components/responses/SaveNotFound'
        '500':
          $ref: '#/components/responses/Error'

    delete:
      summary: Takes user ID from the token, Save ID from the parameters and delete the Save
      operationId: deleteSave
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SaveId'
      responses:
        '200':
          $ref: '#/components/responses/SaveDeleted'
        '404':
          $ref: '#/components/responses/SaveNotFound'
        '500':
          $ref: '#/components/responses/Error'



components:


  schemas:

    Save:
      type: object
      properties:
        _id:
          type: string
          example: 60048e26a8486d510406b33f
        saveData:
          type: object
        userId:
          type: string
          example: 600485e573f5ce001796f558
        createdAt:
          type: string
          format: date
          example: 2021-01-17T19:21:10.492+00:00
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


  responses:

    Save:
      description: Save
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              payload:
                $ref: '#/components/schemas/Save'

    Saves:
      description: Array of Save.
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              payload:
                type: array
                items:
                  $ref: '#/components/schemas/Save'

    SaveDeleted:
      description: Save Deleted
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              payload:
                type: string
                example: 'Deleted'

    SaveNotFound:
      description: No such save
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: No such save

    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Some Error

    Unauthorized:
      description: Unauthorized


  requestBodies:

    SaveData:
      description: Save data
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              saveData:
                type: object


  parameters:

    SaveId:
      name: id
      in: path
      description: Save ID
      required: true
      schema:
        type: string
        example: 60048e26a8486d510406b33f
