openapi: 3.0.0
info:
  title: Arkanoid API
  description: API for Arkanoid game
  version: 1.0.0
  contact:
    name: Vladimir Mazhirin
    url: https://github.com/vladimirm85
    email: vladimirm85@gmail.com
servers:
  - url: https://arkanoid-rss-be.herokuapp.com
    description: Production server
paths:
  /users/{userId}:
    get:
      summary: Get a user by ID
      parameters:
        ...
      responses:
        '200':
          description: A single user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
