export const SET_REG_EMAIL = 'SET_REG_EMAIL';
export const SET_REG_PASSWORD = 'SET_REG_PASSWORD';
export const SET_REG_REPEAT_PASSWORD = 'SET_REG_REPEAT_PASSWORD';
export const SET_REG_ERROR = 'SET_REG_ERROR';
