export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_REPEAT_PASSWORD = 'SET_NEW_REPEAT_PASSWORD';
export const SET_NEW_PASS_ERROR = 'SET_NEW_PASS_ERROR';
export const SET_NEW_PASS_STATUS = 'SET_NEW_PASS_STATUS';
export const SET_NEW_PASS_LOADING = 'SET_NEW_PASS_LOADING';
