export const SET_RESTORE_EMAIL = 'SET_RESTORE_EMAIL';
export const SET_RESTORE_LOADING = 'SET_RESTORE_LOADING';
export const SET_RESTORE_ERROR = 'SET_RESTORE_ERROR';
export const SET_RESTORE_STATUS = 'SET_RESTORE_STATUS';
