export const SET_TOTAL_SCORE = 'SET_TOTAL_SCORE';
export const SET_LEVEL_SCORE = 'SET_LEVEL_SCORE';
export const SET_SCORE_ERROR = 'SET_SCORE_ERROR';
export const SET_SCORE_LOADING = 'SET_SCORE_LOADING';
